# Generated by Django 5.1.4 on 2025-01-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='referencia',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('referencia', 'tamanho_pe')},
        ),
    ]
