# Generated by Django 5.1.4 on 2025-01-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_material_referencia_alter_pedidoitem_pedido_and_more'),
        ('produto', '0001_initial'),
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='material',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.vendedor'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='Produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
