# Generated by Django 5.1.4 on 2025-01-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_status_alter_pedido_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='Produto',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado')], default='Pendente', max_length=50),
        ),
    ]
