# Generated by Django 5.1.4 on 2025-01-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_rename_produto_pedidoitem_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
