# Generated by Django 5.1.4 on 2025-01-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('cliente em espera', 'Cliente em Espera'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50),
        ),
    ]
