# Generated by Django 5.1.4 on 2025-01-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedido_status'),
        ('produto', '0002_produto_cor_produto_costura_produto_obs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='pedido_subpalmilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_subpalmilha', to='produto.produto'),
        ),
    ]
