# Generated by Django 5.1.4 on 2025-01-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedidoitem_pedido_subpalmilha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido_subpalmilha',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='costura',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='sintatico',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
