# Generated by Django 5.1.4 on 2025-01-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_remove_pedidoitem_pedido_subpalmilha_pedidoitem_cor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='sintatico',
            new_name='sintetico',
        ),
    ]
