# Generated by Django 5.1.4 on 2025-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_rename_sintatico_pedidoitem_sintetico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='costura',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='sintetico',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
