# Generated by Django 5.1.4 on 2025-01-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_pedidoitem_costura_alter_pedidoitem_sintetico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='subpalmilha',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='costura',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='sintetico',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
    ]
