# Generated by Django 5.1.4 on 2025-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_pedidoitem_subpalmilha_alter_pedidoitem_costura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='cor',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
    ]
