# Generated by Django 5.1.4 on 2025-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_alter_pedidoitem_cor_alter_pedidoitem_costura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='cor',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='costura',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='sintetico',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='subpalmilha',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
    ]
