# Generated by Django 5.1.4 on 2025-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_alter_pedidoitem_cor_alter_pedidoitem_costura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('cliente em espera', 'Cliente em Espera'), ('Cancelado', 'Cancelado'), ('Aguardando Reposição', 'Aguardando Reposição')], default='Pendente', max_length=50),
        ),
    ]
