# Generated by Django 5.1.4 on 2025-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Cliente em Espera', 'Cliente em Espera'), ('Cancelado', 'Cancelado'), ('Aguardando Reposição', 'Aguardando Reposição')], default='Pendente', max_length=50),
        ),
    ]
