# Generated by Django 5.1.4 on 2025-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Cliente em Espera', 'Cliente em Espera'), ('Cancelado', 'Cancelado'), ('Reposição pendente', 'Reposição pendente')], default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='costura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='sintetico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='subpalmilha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
