# Generated by Django 5.1.4 on 2025-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_alter_pedido_status_alter_pedidoitem_cor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='costura',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='subpalmilha',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='mat_balancinho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='mat_palmilha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='ref_balancinho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='ref_palmilha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='tipo_servico',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('subpalmilha', 'Subpalmilha'), ('costura', 'Costura')], default='nenhum', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Cliente em Espera', 'Cliente em Espera'), ('Cancelado', 'Cancelado'), ('Pedido Separado', 'Pedido Separado'), ('Reposição pendente', 'Reposição pendente')], default='Pendente', max_length=50),
        ),
    ]
