# Generated by Django 5.1.4 on 2025-01-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_remove_pedidoitem_costura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='tamanho_palmilha',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
