# Generated by Django 5.1.4 on 2025-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0022_pedidoitem_tamanho_palmilha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='obs',
            field=models.TextField(blank=True, max_length=90, null=True),
        ),
    ]
