# Generated by Django 5.1.4 on 2025-01-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0023_alter_pedidoitem_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Cliente em Espera', 'Cliente em Espera'), ('Cancelado', 'Cancelado'), ('Pedido Pronto', 'Pedido Pronto'), ('Reposição pendente', 'Reposição Pendente')], default='Pendente', max_length=50),
        ),
    ]
