# Generated by Django 5.1.4 on 2025-01-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0025_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cancelado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='tipo_servico',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('subpalmilha', 'Subpalmilha'), ('costura', 'Costura'), ('subpalmlha Confot', 'Subpalmilha Confot'), ('subpalmilha rv 17', 'Subpalmilha rv 17'), ('subpalmlha com Geleia', 'Subpalmilha com Geleia'), ('subpalmlha confort com cola', 'Subpalmilha confort com cola')], default='nenhum', max_length=50),
        ),
    ]
