# Generated by Django 5.1.4 on 2025-01-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0027_pedido_gerente_cancelamento_alter_pedido_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cancelado',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Cliente em Espera', 'Cliente em Espera'), ('Cancelado', 'Cancelado'), ('Pedido Pronto', 'Pedido Pronto'), ('Reposição Pendente', 'Reposição Pendente')], max_length=20),
        ),
    ]
