# Generated by Django 5.1.4 on 2025-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0029_alter_pedido_gerente_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='tipo_servico',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('subpalmilha', 'Subpalmilha'), ('costura', 'Costura'), ('subpalmlha Confot', 'Subpalmilha Confot'), ('subpalmilha RV 17', 'Subpalmilha rv 17'), ('subpalmlha com Geleia', 'Subpalmilha com Geleia'), ('subpalmlha confort com cola', 'Subpalmilha confort com cola')], default='nenhum', max_length=50),
        ),
    ]
