# Generated by Django 5.1.4 on 2025-02-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0030_alter_pedidoitem_tipo_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='marca',
            field=models.CharField(choices=[('Fibra', 'Fibra'), ('Seltex', 'Seltex')], default='Fibra', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='tipo_servico',
            field=models.CharField(default='nenhum', max_length=50),
        ),
    ]
