# Generated by Django 5.1.4 on 2025-02-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0031_referencia_pedidoitem_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='tamanho_palmilha',
        ),
    ]
