# Generated by Django 5.1.4 on 2025-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0032_remove_pedidoitem_tamanho_palmilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='cor_palmilha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor da Palmilha'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='tam_palmilha',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho Palmilha (mm)'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='espessura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='espessura Solado (mm)'),
        ),
    ]
