# Generated by Django 5.1.4 on 2025-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0034_remove_pedidoitem_sintetico'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='pedidoitem',
        #    name='tam_solado',
        #),
        migrations.AddField(
            model_name='pedidoitem',
            name='espessura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='espessura Solado (mm)'),
        ),
    ]
