# Generated by Django 5.1.4 on 2025-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0035_remove_pedidoitem_tam_solado_pedidoitem_espessura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='espessura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Espessura Solado (mm)'),
        ),
    ]
