# Generated by Django 5.1.4 on 2025-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0036_alter_pedidoitem_espessura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='tam_palmilha',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_balancinho',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_solado',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Produção', 'Em Produção'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=30),
        ),
    ]
