# Generated by Django 5.1.4 on 2025-02-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0038_remove_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_finalizado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização/Cancellation'),
        ),
    ]
