# Generated by Django 5.1.4 on 2025-02-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0040_pedidoitem_descricao_reposicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='descricao_reposicao',
        ),
        migrations.AddField(
            model_name='pedido',
            name='descricao_reposicao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
