# Generated by Django 5.1.4 on 2025-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0041_remove_pedidoitem_descricao_reposicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='marca',
            field=models.CharField(choices=[('Fibra', 'Fibra'), ('Seltex', 'Seltex')], default='', max_length=50),
        ),
    ]
