# Generated by Django 5.1.4 on 2025-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0042_alter_pedidoitem_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='marca',
            field=models.CharField(choices=[('Fibra', 'Fibra'), ('Seltex', 'Seltex'), ('Induma', 'Induma')], default='', max_length=50),
        ),
    ]
