# Generated by Django 5.1.4 on 2025-02-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0043_alter_pedidoitem_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='ref_balancinho',
        ),
    ]
