# Generated by Django 5.1.4 on 2025-01-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_cor_produto_costura_produto_obs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='costura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='sintatico',
        ),
    ]
