# Generated by Django 5.1.4 on 2025-01-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='loja',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
