# Generated by Django 5.1.4 on 2025-01-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='permission_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2'), (3, 'Nível 3'), (4, 'Nivel 4')], default=1),
        ),
    ]
