# Generated by Django 5.1.4 on 2025-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_perfil_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='production_area',
            field=models.CharField(choices=[('solado', 'Solado'), ('balancinho', 'Balancinho')], default='solado', max_length=20, verbose_name='Área de Produção'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='permission_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2'), (3, 'Nível 3'), (4, 'Nível 4')], default=1),
        ),
    ]
