# Generated by Django 5.1.4 on 2025-02-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_perfil_production_area_alter_perfil_permission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='production_area',
            field=models.CharField(choices=[('solado', 'Solado'), ('balancinho', 'Balancinho'), ('vendedor', 'vendedor')], default='solado', max_length=20, verbose_name='Área de Produção'),
        ),
    ]
